"""empty message

Revision ID: 03cb48122bb4
Revises: 434c52f2c728
Create Date: 2020-02-19 16:31:48.202137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03cb48122bb4'
down_revision = '434c52f2c728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_csv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=30), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('brand', sa.String(length=30), nullable=False),
    sa.Column('product_description', sa.String(length=10000), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_csv_brand'), 'product_csv', ['brand'], unique=False)
    op.create_index(op.f('ix_product_csv_color'), 'product_csv', ['color'], unique=False)
    op.create_index(op.f('ix_product_csv_product_description'), 'product_csv', ['product_description'], unique=False)
    op.create_index(op.f('ix_product_csv_product_name'), 'product_csv', ['product_name'], unique=False)
    op.create_index(op.f('ix_product_csv_sku'), 'product_csv', ['sku'], unique=False)
    op.create_index(op.f('ix_product_csv_unit_price'), 'product_csv', ['unit_price'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_csv_unit_price'), table_name='product_csv')
    op.drop_index(op.f('ix_product_csv_sku'), table_name='product_csv')
    op.drop_index(op.f('ix_product_csv_product_name'), table_name='product_csv')
    op.drop_index(op.f('ix_product_csv_product_description'), table_name='product_csv')
    op.drop_index(op.f('ix_product_csv_color'), table_name='product_csv')
    op.drop_index(op.f('ix_product_csv_brand'), table_name='product_csv')
    op.drop_table('product_csv')
    # ### end Alembic commands ###
