"""empty message

Revision ID: 1134fcacd70c
Revises: 5a33884cb2e7
Create Date: 2020-02-19 16:26:00.874711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1134fcacd70c'
down_revision = '5a33884cb2e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_csv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.String(length=30), nullable=False),
    sa.Column('total_price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_csv_purchase_date'), 'order_csv', ['purchase_date'], unique=False)
    op.create_index(op.f('ix_order_csv_total_price'), 'order_csv', ['total_price'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_csv_total_price'), table_name='order_csv')
    op.drop_index(op.f('ix_order_csv_purchase_date'), table_name='order_csv')
    op.drop_table('order_csv')
    # ### end Alembic commands ###
