"""empty message

Revision ID: 50990a9c7917
Revises: 37502c1f9421
Create Date: 2020-02-18 10:15:33.825315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50990a9c7917'
down_revision = '37502c1f9421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_templates', sa.Column('email_content', sa.String(length=5000), nullable=True))
    op.create_index(op.f('ix_email_templates_email_content'), 'email_templates', ['email_content'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_templates_email_content'), table_name='email_templates')
    op.drop_column('email_templates', 'email_content')
    # ### end Alembic commands ###
