"""empty message

Revision ID: 5a33884cb2e7
Revises: 9e78e45b2c55
Create Date: 2020-02-19 16:07:26.277809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a33884cb2e7'
down_revision = '9e78e45b2c55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_csv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('gender', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('zipcode', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('registration_date', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_csv_address'), 'customer_csv', ['address'], unique=False)
    op.create_index(op.f('ix_customer_csv_age'), 'customer_csv', ['age'], unique=False)
    op.create_index(op.f('ix_customer_csv_email'), 'customer_csv', ['email'], unique=False)
    op.create_index(op.f('ix_customer_csv_first_name'), 'customer_csv', ['first_name'], unique=False)
    op.create_index(op.f('ix_customer_csv_gender'), 'customer_csv', ['gender'], unique=False)
    op.create_index(op.f('ix_customer_csv_last_name'), 'customer_csv', ['last_name'], unique=False)
    op.create_index(op.f('ix_customer_csv_phone_number'), 'customer_csv', ['phone_number'], unique=False)
    op.create_index(op.f('ix_customer_csv_state'), 'customer_csv', ['state'], unique=False)
    op.create_index(op.f('ix_customer_csv_zipcode'), 'customer_csv', ['zipcode'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_csv_zipcode'), table_name='customer_csv')
    op.drop_index(op.f('ix_customer_csv_state'), table_name='customer_csv')
    op.drop_index(op.f('ix_customer_csv_phone_number'), table_name='customer_csv')
    op.drop_index(op.f('ix_customer_csv_last_name'), table_name='customer_csv')
    op.drop_index(op.f('ix_customer_csv_gender'), table_name='customer_csv')
    op.drop_index(op.f('ix_customer_csv_first_name'), table_name='customer_csv')
    op.drop_index(op.f('ix_customer_csv_email'), table_name='customer_csv')
    op.drop_index(op.f('ix_customer_csv_age'), table_name='customer_csv')
    op.drop_index(op.f('ix_customer_csv_address'), table_name='customer_csv')
    op.drop_table('customer_csv')
    # ### end Alembic commands ###
