"""empty message

Revision ID: 7efcd665f1c8
Revises: 
Create Date: 2020-02-17 19:18:09.525336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7efcd665f1c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_details',
    sa.Column('customer_unique_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=True),
    sa.Column('customer_email', sa.String(length=200), nullable=True),
    sa.Column('total_shopping_by_customer', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('customer_unique_id')
    )
    op.create_index(op.f('ix_customer_details_customer_email'), 'customer_details', ['customer_email'], unique=True)
    op.create_index(op.f('ix_customer_details_customer_name'), 'customer_details', ['customer_name'], unique=False)
    op.create_index(op.f('ix_customer_details_total_shopping_by_customer'), 'customer_details', ['total_shopping_by_customer'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_details_total_shopping_by_customer'), table_name='customer_details')
    op.drop_index(op.f('ix_customer_details_customer_name'), table_name='customer_details')
    op.drop_index(op.f('ix_customer_details_customer_email'), table_name='customer_details')
    op.drop_table('customer_details')
    # ### end Alembic commands ###
