"""empty message

Revision ID: 92389ac46fb9
Revises: 50990a9c7917
Create Date: 2020-02-18 11:29:21.220775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92389ac46fb9'
down_revision = '50990a9c7917'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_email_templates_is_template_approved', table_name='email_templates')
    op.drop_column('email_templates', 'is_template_approved')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_templates', sa.Column('is_template_approved', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_index('ix_email_templates_is_template_approved', 'email_templates', ['is_template_approved'], unique=False)
    # ### end Alembic commands ###
