"""empty message

Revision ID: 9b52c8db3c9f
Revises: 01d0d8b09683
Create Date: 2020-02-18 11:49:38.595241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b52c8db3c9f'
down_revision = '01d0d8b09683'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_email_templates_email_type', table_name='email_templates')
    op.create_index(op.f('ix_email_templates_email_type'), 'email_templates', ['email_type'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_templates_email_type'), table_name='email_templates')
    op.create_index('ix_email_templates_email_type', 'email_templates', ['email_type'], unique=False)
    # ### end Alembic commands ###
