"""empty message

Revision ID: a4d328c070da
Revises: 92389ac46fb9
Create Date: 2020-02-18 11:37:48.449956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4d328c070da'
down_revision = '92389ac46fb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_templates', sa.Column('is_template_approved', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_email_templates_is_template_approved'), 'email_templates', ['is_template_approved'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_templates_is_template_approved'), table_name='email_templates')
    op.drop_column('email_templates', 'is_template_approved')
    # ### end Alembic commands ###
