"""empty message

Revision ID: cb344583c923
Revises: fc1d1dfb101c
Create Date: 2020-02-19 14:30:30.278043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb344583c923'
down_revision = 'fc1d1dfb101c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_csv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('gender', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('zipcode', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('registration_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_csv_address'), 'customer_csv', ['address'], unique=False)
    op.create_index(op.f('ix_customer_csv_age'), 'customer_csv', ['age'], unique=False)
    op.create_index(op.f('ix_customer_csv_email'), 'customer_csv', ['email'], unique=False)
    op.create_index(op.f('ix_customer_csv_first_name'), 'customer_csv', ['first_name'], unique=False)
    op.create_index(op.f('ix_customer_csv_gender'), 'customer_csv', ['gender'], unique=False)
    op.create_index(op.f('ix_customer_csv_last_name'), 'customer_csv', ['last_name'], unique=False)
    op.create_index(op.f('ix_customer_csv_phone_number'), 'customer_csv', ['phone_number'], unique=False)
    op.create_index(op.f('ix_customer_csv_registration_date'), 'customer_csv', ['registration_date'], unique=False)
    op.create_index(op.f('ix_customer_csv_state'), 'customer_csv', ['state'], unique=False)
    op.create_index(op.f('ix_customer_csv_zipcode'), 'customer_csv', ['zipcode'], unique=False)
    op.create_table('order_csv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('total_price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_csv_purchase_date'), 'order_csv', ['purchase_date'], unique=False)
    op.create_index(op.f('ix_order_csv_total_price'), 'order_csv', ['total_price'], unique=False)
    op.create_table('product_csv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('brand', sa.String(length=30), nullable=False),
    sa.Column('product_description', sa.String(length=200), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_csv_brand'), 'product_csv', ['brand'], unique=False)
    op.create_index(op.f('ix_product_csv_color'), 'product_csv', ['color'], unique=False)
    op.create_index(op.f('ix_product_csv_product_description'), 'product_csv', ['product_description'], unique=False)
    op.create_index(op.f('ix_product_csv_product_name'), 'product_csv', ['product_name'], unique=False)
    op.create_index(op.f('ix_product_csv_sku'), 'product_csv', ['sku'], unique=False)
    op.create_index(op.f('ix_product_csv_unit_price'), 'product_csv', ['unit_price'], unique=False)
    op.create_table('review_csv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_product_id', sa.Integer(), nullable=False),
    sa.Column('product_rating', sa.Integer(), nullable=False),
    sa.Column('review_title', sa.String(length=30), nullable=False),
    sa.Column('review_details', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_csv_product_rating'), 'review_csv', ['product_rating'], unique=False)
    op.create_index(op.f('ix_review_csv_review_details'), 'review_csv', ['review_details'], unique=False)
    op.create_index(op.f('ix_review_csv_review_title'), 'review_csv', ['review_title'], unique=False)
    op.create_index(op.f('ix_review_csv_user_product_id'), 'review_csv', ['user_product_id'], unique=False)
    op.create_table('user_product_list_csv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('orderid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_product_list_csv_orderid'), 'user_product_list_csv', ['orderid'], unique=False)
    op.create_index(op.f('ix_user_product_list_csv_product_id'), 'user_product_list_csv', ['product_id'], unique=False)
    op.create_index(op.f('ix_user_product_list_csv_quantity'), 'user_product_list_csv', ['quantity'], unique=False)
    op.create_index(op.f('ix_user_product_list_csv_user_id'), 'user_product_list_csv', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_product_list_csv_user_id'), table_name='user_product_list_csv')
    op.drop_index(op.f('ix_user_product_list_csv_quantity'), table_name='user_product_list_csv')
    op.drop_index(op.f('ix_user_product_list_csv_product_id'), table_name='user_product_list_csv')
    op.drop_index(op.f('ix_user_product_list_csv_orderid'), table_name='user_product_list_csv')
    op.drop_table('user_product_list_csv')
    op.drop_index(op.f('ix_review_csv_user_product_id'), table_name='review_csv')
    op.drop_index(op.f('ix_review_csv_review_title'), table_name='review_csv')
    op.drop_index(op.f('ix_review_csv_review_details'), table_name='review_csv')
    op.drop_index(op.f('ix_review_csv_product_rating'), table_name='review_csv')
    op.drop_table('review_csv')
    op.drop_index(op.f('ix_product_csv_unit_price'), table_name='product_csv')
    op.drop_index(op.f('ix_product_csv_sku'), table_name='product_csv')
    op.drop_index(op.f('ix_product_csv_product_name'), table_name='product_csv')
    op.drop_index(op.f('ix_product_csv_product_description'), table_name='product_csv')
    op.drop_index(op.f('ix_product_csv_color'), table_name='product_csv')
    op.drop_index(op.f('ix_product_csv_brand'), table_name='product_csv')
    op.drop_table('product_csv')
    op.drop_index(op.f('ix_order_csv_total_price'), table_name='order_csv')
    op.drop_index(op.f('ix_order_csv_purchase_date'), table_name='order_csv')
    op.drop_table('order_csv')
    op.drop_index(op.f('ix_customer_csv_zipcode'), table_name='customer_csv')
    op.drop_index(op.f('ix_customer_csv_state'), table_name='customer_csv')
    op.drop_index(op.f('ix_customer_csv_registration_date'), table_name='customer_csv')
    op.drop_index(op.f('ix_customer_csv_phone_number'), table_name='customer_csv')
    op.drop_index(op.f('ix_customer_csv_last_name'), table_name='customer_csv')
    op.drop_index(op.f('ix_customer_csv_gender'), table_name='customer_csv')
    op.drop_index(op.f('ix_customer_csv_first_name'), table_name='customer_csv')
    op.drop_index(op.f('ix_customer_csv_email'), table_name='customer_csv')
    op.drop_index(op.f('ix_customer_csv_age'), table_name='customer_csv')
    op.drop_index(op.f('ix_customer_csv_address'), table_name='customer_csv')
    op.drop_table('customer_csv')
    # ### end Alembic commands ###
