"""empty message

Revision ID: fc1d1dfb101c
Revises: 0c8bd1b7c70a
Create Date: 2020-02-19 09:44:38.746614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc1d1dfb101c'
down_revision = '0c8bd1b7c70a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_templates', sa.Column('title', sa.String(length=30), nullable=False))
    op.create_index(op.f('ix_email_templates_title'), 'email_templates', ['title'], unique=True)
    op.drop_index('ix_email_templates_email_type', table_name='email_templates')
    op.create_index(op.f('ix_email_templates_email_type'), 'email_templates', ['email_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_templates_email_type'), table_name='email_templates')
    op.create_index('ix_email_templates_email_type', 'email_templates', ['email_type'], unique=True)
    op.drop_index(op.f('ix_email_templates_title'), table_name='email_templates')
    op.drop_column('email_templates', 'title')
    # ### end Alembic commands ###
