"""empty message

Revision ID: fd6f07995bf4
Revises: cb344583c923
Create Date: 2020-02-19 15:53:39.440171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd6f07995bf4'
down_revision = 'cb344583c923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customer_csv_registration_date', table_name='customer_csv')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_customer_csv_registration_date', 'customer_csv', ['registration_date'], unique=False)
    # ### end Alembic commands ###
